# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(234, 345)
        self.text = QtWidgets.QLabel(parent=Dialog)
        self.text.setGeometry(QtCore.QRect(20, 30, 199, 13))
        self.text.setObjectName("text")
        self.number = QtWidgets.QLabel(parent=Dialog)
        self.number.setGeometry(QtCore.QRect(100, 160, 20, 13))
        self.number.setObjectName("number")
        self.btn = QtWidgets.QPushButton(parent=Dialog)
        self.btn.setGeometry(QtCore.QRect(80, 290, 75, 23))
        self.btn.setObjectName("btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.text.setText(_translate("Dialog", "Якщо ти нажимаєш число збільшується"))
        self.number.setText(_translate("Dialog", "num"))
        self.btn.setText(_translate("Dialog", "Нажми!"))
